CREATE TABLE bidding_project (
                                 id INT PRIMARY KEY AUTO_INCREMENT COMMENT '序号',
                                 bidding_status VARCHAR(50) COMMENT '投标状态(未投标/已投标/已截止)',
                                 bidding_name VARCHAR(255) COMMENT '标的发布名称',
                                 bid_result VARCHAR(50) COMMENT '中标结果(未开标/已中标/未中标)',
                                 bidding_end_time DATETIME COMMENT '投标结束时间',
                                 registration_status VARCHAR(50) COMMENT '报名状态(未报名/已报名/已截止)',
                                 bidding_progress VARCHAR(50) COMMENT '投标进度(未开始/进行中/已完成)',
                                 project_title VARCHAR(255) COMMENT '项目标题',
                                 publish_time DATETIME COMMENT '发布时间',
                                 publish_enterprise VARCHAR(255) COMMENT '发布企业',
                                 project_summary TEXT COMMENT '内容简介',
                                 id_card VARCHAR(18) COMMENT '身份证号',
                                 signature_url VARCHAR(255) COMMENT '签字图片路径',
                                 id_card_url VARCHAR(255) COMMENT '身份证图片路径',
                                 file_url VARCHAR(255) COMMENT '上传文件路径',
                                 create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                 update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);

-- 插入测试数据
INSERT INTO bidding_project (
    bidding_status,
    bidding_name,
    bid_result,
    bidding_end_time,
    registration_status,
    bidding_progress,
    project_title,
    publish_time,
    publish_enterprise,
    project_summary,
    id_card,
    signature_url,
    id_card_url,
    file_url
) VALUES
      (
          '未投标',
          '2024年度办公用品采购标的',
          '未开标',
          '2024-04-15 17:00:00',
          '已报名',
          '未开始',
          '2024年度办公用品采购项目',
          '2024-03-15 10:00:00',
          '某某科技有限公司',
          '本项目为年度办公用品集中采购项目，包括但不限于办公文具、打印纸等办公耗材',
          '110101199001011234',
          'files/signature/sign1.png',
          'files/idcard/card1.png',
          'files/bidding/doc1.pdf'
      ),
      (
          '已投标',
          '环保设备采购标的',
          '未开标',
          '2024-04-20 17:00:00',
          '已报名',
          '进行中',
          '环保监测设备采购项目',
          '2024-03-16 14:30:00',
          '某某环保科技有限公司',
          '采购空气质量监测设备、水质监测设备等环保监测设备',
          '110101199001011235',
          'files/signature/sign2.png',
          'files/idcard/card2.png',
          'files/bidding/doc2.pdf'
      ),
      (
          '已投标',
          '新能源设备采购标的',
          '已中标',
          '2024-03-10 17:00:00',
          '已截止',
          '已完成',
          '新能源发电设备采购项目',
          '2024-02-25 09:00:00',
          '某某新能源有限公司',
          '采购太阳能发电板、储能设备等新能源设备',
          '110101199001011236',
          'files/signature/sign3.png',
          'files/idcard/card3.png',
          'files/bidding/doc3.pdf'
      );