CREATE TABLE mesProductCheck (
                                 id BIGINT COMMENT '编号' primary key AUTO_INCREMENT,
                                 checkDate DATETIME COMMENT '检验时间',
                                 checkItemName VARCHAR(255) COMMENT '检验项',
                                 checkQuantity DOUBLE COMMENT '抽检数量',
                                 checkResult VARCHAR(10) COMMENT '检验结果：0不合格，1合格',
                                 checkStandardId BIGINT COMMENT '检验标准编号',
                                 checkUser VARCHAR(255) COMMENT '检验人',
                                 checkValue DOUBLE COMMENT '检验值',
                                 createBy VARCHAR(255) COMMENT '创建用户',
                                 materialBatchNo VARCHAR(255) COMMENT '检验批次',
                                 materialCode VARCHAR(255) COMMENT '物料编码',
                                 materialId BIGINT COMMENT '物料档案编号',
                                 materialModel VARCHAR(255) COMMENT '物料型号',
                                 materialName VARCHAR(255) COMMENT '产品名称',
                                 materialSpecification VARCHAR(255) COMMENT '物料规格',
                                 materialUnit VARCHAR(255) COMMENT '物料单位',
                                 `maxValue` DOUBLE COMMENT '阈值上限',
                                 `minValue` DOUBLE COMMENT '阈值下限',
                                 productDate DATETIME COMMENT '生产日期',
                                 productFinishId BIGINT COMMENT '完工单id',
                                 productFinishNo VARCHAR(255) COMMENT '完工单号',
                                 productJobId BIGINT COMMENT '生产作业编号',
                                 productJobName VARCHAR(255) COMMENT '作业名称',
                                 productLineId BIGINT COMMENT '生产线编号',
                                 productLineName VARCHAR(255) COMMENT '生产线名称',
                                 productPlanId BIGINT COMMENT '生产计划编号',
                                 productPlanNo VARCHAR(255) COMMENT '计划编号',
                                 productQuantity DOUBLE COMMENT '生产数量',
                                 productScheduleId BIGINT COMMENT '计划排产编号',
                                 qualifiedRate DOUBLE COMMENT '合格率',
                                 remark TEXT COMMENT '备注',
                                 searchValue TEXT COMMENT '搜索值',
                                 serialNo VARCHAR(255) COMMENT '流水号',
                                 updateBy VARCHAR(255) COMMENT '更新用户',
                                 updateTime DATETIME COMMENT '更新时间',
                                 params JSON COMMENT '其他参数'
) COMMENT='产品检验单';

INSERT INTO mesProductCheck (
    id, checkDate, checkItemName, checkQuantity, checkResult, checkStandardId,
    checkUser, checkValue, createBy, materialBatchNo, materialCode,
    materialId, materialModel, materialName, materialSpecification,
    materialUnit, `maxValue`, `minValue`, productDate, productFinishId,
    productFinishNo, productJobId, productJobName, productLineId,
    productLineName, productPlanId, productPlanNo, productQuantity,
    productScheduleId, qualifiedRate, remark, searchValue, serialNo,
    updateBy, updateTime, params
) VALUES
      (
          1, '2025-03-11 10:00:00', '外观检查', 10, '1', 1001,
          '张三', 95.5, 'admin', 'Batch001', 'MAT001',
          1, 'ModelA', '产品A', '规格1', '件',
          100.0, 90.0, '2025-03-10 08:00:00', 1001,
          'PF001', 2001, '作业1', 3001,
          '生产线1', 4001, '计划1', 100,
          5001, 95.0, '合格率很高', '', 'SN001',
          'admin', '2025-03-11 10:05:00', '{"key": "value"}'
      ),
      (
          2, '2025-03-11 11:00:00', '尺寸测量', 5, '0', 1002,
          '李四', 85.0, 'admin', 'Batch002', 'MAT002',
          2, 'ModelB', '产品B', '规格2', '米',
          120.0, 80.0, '2025-03-10 09:00:00', 1002,
          'PF002', 2002, '作业2', 3002,
          '生产线2', 4002, '计划2', 200,
          5002, 80.0, '尺寸不合格', '', 'SN002',
          'admin', '2025-03-11 11:05:00', '{"key2": "value2"}'
      ),
      (
          3, '2025-03-11 12:00:00', '性能测试', 20, '1', 1003,
          '王五', 98.0, 'admin', 'Batch003', 'MAT003',
          3, 'ModelC', '产品C', '规格3', '套',
          110.0, 95.0, '2025-03-10 10:00:00', 1003,
          'PF003', 2003, '作业3', 3003,
          '生产线3', 4003, '计划3', 300,
          5003, 99.0, '性能良好', '', 'SN003',
          'admin', '2025-03-11 12:05:00', '{"key3": "value3"}'
      );